/*
 * SMAJ-RTNIDS 2012-2013
 */

package GUI;

import java.awt.Dialog;
import java.awt.FileDialog;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Mrinal Bhalerao
 */
public class SelectFrame extends javax.swing.JFrame {
    String testPath, trPath, ktestPath, ktrPath,logfile,ResPath,anapath;
    int flag=0;
    DATAGEN dg=null;
    kNNStart ks= new kNNStart();               
    convertdatats cds =new convertdatats();
    /** Creates new form SelectFrame */
    public SelectFrame() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        SMAJ_RTNIDS = new javax.swing.JTabbedPane();
        SMAJ_RTNIDS1 = new javax.swing.JTabbedPane();
        DecTreePanel1 = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jButton32 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jButton43 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        TITLE1 = new javax.swing.JLabel();
        DecTreePanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jButton31 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton44 = new javax.swing.JButton();
        TITLE2 = new javax.swing.JLabel();
        DecTreePanel3 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jButton56 = new javax.swing.JButton();
        AnalyseDTResult9 = new javax.swing.JButton();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        AnalyseDTResult11 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        AnalyseDTResult12 = new javax.swing.JButton();
        AnalyseDTResult15 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        TITLE3 = new javax.swing.JLabel();
        DecTreePanel4 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jLabel50 = new javax.swing.JLabel();
        TITLE4 = new javax.swing.JLabel();
        SMAJ_RTNIDS2 = new javax.swing.JTabbedPane();
        DecTreePanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jButton38 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        TITLE5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        DecTreePanel6 = new javax.swing.JPanel();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jButton42 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        TITLE6 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        DecTreePanel7 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        AnalyseDTResult10 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        AnalyseDTResult13 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        TITLE7 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        DecTreePanel8 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        TITLE8 = new javax.swing.JLabel();
        AnalysisPanel = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        TITLE9 = new javax.swing.JLabel();
        ResultPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        TITLE10 = new javax.swing.JLabel();
        TITLE = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setText("Decision Tree Implementation");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RT-NIDS [SMAJ GROUP]");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 850, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(new java.awt.Color(51, 51, 51));
        setName("MainFrame"); // NOI18N

        SMAJ_RTNIDS.setBackground(new java.awt.Color(102, 102, 102));
        SMAJ_RTNIDS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N
        SMAJ_RTNIDS.setForeground(new java.awt.Color(255, 255, 255));
        SMAJ_RTNIDS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SMAJ_RTNIDS.setFont(new java.awt.Font("Verdana", 1, 14));

        SMAJ_RTNIDS1.setBackground(new java.awt.Color(102, 102, 102));
        SMAJ_RTNIDS1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N
        SMAJ_RTNIDS1.setForeground(new java.awt.Color(255, 255, 255));
        SMAJ_RTNIDS1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        SMAJ_RTNIDS1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SMAJ_RTNIDS1.setFont(new java.awt.Font("Verdana", 1, 14));

        DecTreePanel1.setBackground(new java.awt.Color(255, 255, 255));
        DecTreePanel1.setBorder(new javax.swing.border.MatteBorder(null));
        DecTreePanel1.setForeground(new java.awt.Color(255, 153, 153));
        DecTreePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton27.setBackground(new java.awt.Color(0, 204, 204));
        jButton27.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("Start Training");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        DecTreePanel1.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 170, 30));

        jButton29.setBackground(new java.awt.Color(0, 204, 204));
        jButton29.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("Last Train Result");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        DecTreePanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 170, 30));

        jButton33.setBackground(new java.awt.Color(0, 204, 204));
        jButton33.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setText("Training File");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        DecTreePanel1.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 170, 30));

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 14));
        jLabel30.setForeground(new java.awt.Color(153, 153, 255));
        DecTreePanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 760, 30));

        jTextArea11.setColumns(20);
        jTextArea11.setEditable(false);
        jTextArea11.setFont(new java.awt.Font("Verdana", 1, 14));
        jTextArea11.setForeground(new java.awt.Color(51, 0, 51));
        jTextArea11.setRows(5);
        jScrollPane11.setViewportView(jTextArea11);

        DecTreePanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 1230, 310));

        jButton32.setBackground(new java.awt.Color(0, 204, 204));
        jButton32.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setText("Old Train Log");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        DecTreePanel1.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 170, 30));

        jLabel39.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel39.setForeground(new java.awt.Color(255, 153, 153));
        jLabel39.setText("View old log files:");
        DecTreePanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, 30));

        jLabel41.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel41.setForeground(new java.awt.Color(255, 153, 153));
        jLabel41.setText("Training File:");
        DecTreePanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        jLabel42.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel42.setForeground(new java.awt.Color(255, 153, 153));
        jLabel42.setText("View Result :");
        DecTreePanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jLabel43.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel43.setForeground(new java.awt.Color(255, 153, 153));
        jLabel43.setText("Start training: ");
        DecTreePanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, 30));

        jButton43.setBackground(new java.awt.Color(0, 204, 204));
        jButton43.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton43.setForeground(new java.awt.Color(255, 255, 255));
        jButton43.setText("Graph");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        DecTreePanel1.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 130, 30));

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel22.setForeground(new java.awt.Color(0, 204, 204));
        jLabel22.setText("Decision Tree Implementation");
        DecTreePanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 310, 20));

        TITLE1.setFont(new java.awt.Font("Tahoma", 1, 18));
        TITLE1.setForeground(new java.awt.Color(102, 102, 255));
        TITLE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/5.png"))); // NOI18N
        DecTreePanel1.add(TITLE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 230, 120));

        SMAJ_RTNIDS1.addTab("Training", DecTreePanel1);

        DecTreePanel2.setBackground(new java.awt.Color(255, 255, 255));
        DecTreePanel2.setBorder(new javax.swing.border.MatteBorder(null));
        DecTreePanel2.setForeground(new java.awt.Color(255, 153, 153));
        DecTreePanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel17.setForeground(new java.awt.Color(0, 204, 204));
        jLabel17.setText("Decision Tree Implementation");
        DecTreePanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 310, 20));

        jButton28.setBackground(new java.awt.Color(0, 204, 204));
        jButton28.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setText("Test");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        DecTreePanel2.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 170, 30));

        jButton30.setBackground(new java.awt.Color(0, 204, 204));
        jButton30.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setText("Last Test Result");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        DecTreePanel2.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 170, 30));

        jButton34.setBackground(new java.awt.Color(0, 204, 204));
        jButton34.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setText("Testing File");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        DecTreePanel2.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 170, 30));

        jLabel33.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel33.setForeground(new java.awt.Color(255, 153, 153));
        jLabel33.setText("View Result :");
        DecTreePanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 14));
        jLabel34.setForeground(new java.awt.Color(153, 153, 255));
        DecTreePanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 760, 30));

        jLabel35.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel35.setForeground(new java.awt.Color(255, 153, 153));
        jLabel35.setText("View old log files:");
        DecTreePanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, 30));

        jTextArea10.setColumns(20);
        jTextArea10.setEditable(false);
        jTextArea10.setFont(new java.awt.Font("Verdana", 1, 14));
        jTextArea10.setForeground(new java.awt.Color(51, 0, 51));
        jTextArea10.setRows(5);
        jScrollPane10.setViewportView(jTextArea10);

        DecTreePanel2.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 1230, 310));

        jButton31.setBackground(new java.awt.Color(0, 204, 204));
        jButton31.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("Log Files");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        DecTreePanel2.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 170, 30));

        jLabel37.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel37.setForeground(new java.awt.Color(255, 153, 153));
        jLabel37.setText("Testing File:");
        DecTreePanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        jLabel38.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel38.setForeground(new java.awt.Color(255, 153, 153));
        jLabel38.setText("Start testing: ");
        DecTreePanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, 30));

        jButton44.setBackground(new java.awt.Color(0, 204, 204));
        jButton44.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton44.setForeground(new java.awt.Color(255, 255, 255));
        jButton44.setText("Graph");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        DecTreePanel2.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 130, 30));

        TITLE2.setFont(new java.awt.Font("Tahoma", 1, 18));
        TITLE2.setForeground(new java.awt.Color(102, 102, 255));
        TITLE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/5.png"))); // NOI18N
        DecTreePanel2.add(TITLE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 230, 120));

        SMAJ_RTNIDS1.addTab("Testing", DecTreePanel2);

        DecTreePanel3.setBackground(new java.awt.Color(255, 255, 255));
        DecTreePanel3.setBorder(new javax.swing.border.MatteBorder(null));
        DecTreePanel3.setForeground(new java.awt.Color(255, 153, 153));
        DecTreePanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel48.setForeground(new java.awt.Color(0, 204, 204));
        jLabel48.setText("Decision Tree Implementation");
        DecTreePanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 310, 20));

        jLabel51.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel51.setForeground(new java.awt.Color(255, 153, 153));
        jLabel51.setText("View Log File:");
        DecTreePanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, 30));

        jButton56.setBackground(new java.awt.Color(0, 204, 204));
        jButton56.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton56.setForeground(new java.awt.Color(255, 255, 255));
        jButton56.setText("Select file");
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });
        DecTreePanel3.add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 140, 30));

        AnalyseDTResult9.setBackground(new java.awt.Color(0, 204, 204));
        AnalyseDTResult9.setFont(new java.awt.Font("Verdana", 1, 14));
        AnalyseDTResult9.setForeground(new java.awt.Color(255, 255, 255));
        AnalyseDTResult9.setText("Last Analysis Result");
        AnalyseDTResult9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyseDTResult9ActionPerformed(evt);
            }
        });
        DecTreePanel3.add(AnalyseDTResult9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 190, 30));
        DecTreePanel3.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 370, 10));

        jLabel52.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel52.setForeground(new java.awt.Color(255, 153, 153));
        jLabel52.setText("Analysis using counts:");
        DecTreePanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 20));

        jLabel31.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel31.setForeground(new java.awt.Color(153, 153, 255));
        jLabel31.setText("NORMAL");
        DecTreePanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jTextField10.setFont(new java.awt.Font("Verdana", 1, 14));
        DecTreePanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 80, 30));

        jLabel53.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel53.setForeground(new java.awt.Color(153, 153, 255));
        jLabel53.setText("DOS");
        DecTreePanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 20));

        jTextField11.setFont(new java.awt.Font("Verdana", 1, 14));
        DecTreePanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 80, 30));

        jLabel54.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel54.setForeground(new java.awt.Color(153, 153, 255));
        jLabel54.setText("PROBE");
        DecTreePanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 20));

        jTextField12.setFont(new java.awt.Font("Verdana", 1, 14));
        DecTreePanel3.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 80, 30));

        jButton59.setBackground(new java.awt.Color(0, 204, 204));
        jButton59.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton59.setForeground(new java.awt.Color(255, 255, 255));
        jButton59.setText("Start Analysis");
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });
        DecTreePanel3.add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 140, 30));

        jButton60.setBackground(new java.awt.Color(0, 204, 204));
        jButton60.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton60.setForeground(new java.awt.Color(255, 255, 255));
        jButton60.setText("Start Analysis");
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        DecTreePanel3.add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 140, 30));

        AnalyseDTResult11.setBackground(new java.awt.Color(0, 204, 204));
        AnalyseDTResult11.setFont(new java.awt.Font("Verdana", 1, 14));
        AnalyseDTResult11.setForeground(new java.awt.Color(255, 255, 255));
        AnalyseDTResult11.setText("Open Last Log");
        AnalyseDTResult11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyseDTResult11ActionPerformed(evt);
            }
        });
        DecTreePanel3.add(AnalyseDTResult11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 180, 30));

        jButton63.setBackground(new java.awt.Color(0, 204, 204));
        jButton63.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton63.setForeground(new java.awt.Color(255, 255, 255));
        jButton63.setText("Select File");
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        DecTreePanel3.add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 140, 30));

        jLabel55.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel55.setForeground(new java.awt.Color(255, 153, 153));
        jLabel55.setText("Analysis using answer class:");
        DecTreePanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 20));

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 14));
        jLabel36.setForeground(new java.awt.Color(153, 153, 255));
        DecTreePanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 790, 30));
        DecTreePanel3.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 370, 10));

        jTextArea8.setColumns(20);
        jTextArea8.setEditable(false);
        jTextArea8.setFont(new java.awt.Font("Verdana", 1, 14));
        jTextArea8.setForeground(new java.awt.Color(51, 0, 51));
        jTextArea8.setRows(5);
        jScrollPane8.setViewportView(jTextArea8);

        DecTreePanel3.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 810, 370));

        AnalyseDTResult12.setBackground(new java.awt.Color(0, 204, 204));
        AnalyseDTResult12.setFont(new java.awt.Font("Verdana", 1, 14));
        AnalyseDTResult12.setForeground(new java.awt.Color(255, 255, 255));
        AnalyseDTResult12.setText("Open Old Log");
        AnalyseDTResult12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyseDTResult12ActionPerformed(evt);
            }
        });
        DecTreePanel3.add(AnalyseDTResult12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 180, 30));

        AnalyseDTResult15.setBackground(new java.awt.Color(0, 204, 204));
        AnalyseDTResult15.setFont(new java.awt.Font("Verdana", 1, 14));
        AnalyseDTResult15.setForeground(new java.awt.Color(255, 255, 255));
        AnalyseDTResult15.setText("Last Combined Result");
        AnalyseDTResult15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyseDTResult15ActionPerformed(evt);
            }
        });
        DecTreePanel3.add(AnalyseDTResult15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 210, 30));

        jButton45.setBackground(new java.awt.Color(0, 204, 204));
        jButton45.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton45.setForeground(new java.awt.Color(255, 255, 255));
        jButton45.setText("Graph");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        DecTreePanel3.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 130, 30));

        TITLE3.setFont(new java.awt.Font("Tahoma", 1, 18));
        TITLE3.setForeground(new java.awt.Color(102, 102, 255));
        TITLE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/5.png"))); // NOI18N
        DecTreePanel3.add(TITLE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 220, 120));

        SMAJ_RTNIDS1.addTab("Analysis", DecTreePanel3);

        DecTreePanel4.setBackground(new java.awt.Color(255, 255, 255));
        DecTreePanel4.setBorder(new javax.swing.border.MatteBorder(null));
        DecTreePanel4.setForeground(new java.awt.Color(255, 153, 153));
        DecTreePanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea9.setColumns(20);
        jTextArea9.setEditable(false);
        jTextArea9.setFont(new java.awt.Font("Verdana", 1, 14));
        jTextArea9.setForeground(new java.awt.Color(51, 0, 51));
        jTextArea9.setRows(5);
        jTextArea9.setText("\nA decision tree is a decision support tool that uses a tree-like  graph or model of decisions and their possible consequences,\n including chance event outcomes, resource costs, and utility.\n It is one way to display an algorithm. \n     Decision trees are commonly used in operations research,  specifically in decision analysis, to help identify a strategy\n most likely to reach a goal. If in practice decisions have to be taken online with no recall under incomplete knowledge,\n a decision tree should be paralleled by a probability model as a best choice model or online selection model algorithm.\n     Another use of decision trees is as a descriptive means for calculating conditional probabilities\n    In decision analysis, a \"decision tree\" — and the closely related influence diagram — is used as a visual and analytical \ndecision support tool, where the expected values (or expected utility) of competing alternatives are calculated.\n");
        jScrollPane9.setViewportView(jTextArea9);

        DecTreePanel4.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 970, 300));

        jLabel50.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel50.setForeground(new java.awt.Color(0, 204, 204));
        jLabel50.setText("Decision Tree Information");
        DecTreePanel4.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 310, 20));

        TITLE4.setFont(new java.awt.Font("Tahoma", 1, 18));
        TITLE4.setForeground(new java.awt.Color(102, 102, 255));
        TITLE4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/5.png"))); // NOI18N
        DecTreePanel4.add(TITLE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 230, 120));

        SMAJ_RTNIDS1.addTab("Help", DecTreePanel4);

        SMAJ_RTNIDS.addTab("Decision Tree", SMAJ_RTNIDS1);

        SMAJ_RTNIDS2.setBackground(new java.awt.Color(102, 102, 102));
        SMAJ_RTNIDS2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N
        SMAJ_RTNIDS2.setForeground(new java.awt.Color(255, 255, 255));
        SMAJ_RTNIDS2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        SMAJ_RTNIDS2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SMAJ_RTNIDS2.setFont(new java.awt.Font("Verdana", 1, 14));

        DecTreePanel5.setBackground(new java.awt.Color(255, 255, 255));
        DecTreePanel5.setBorder(new javax.swing.border.MatteBorder(null));
        DecTreePanel5.setForeground(new java.awt.Color(255, 153, 153));
        DecTreePanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel18.setForeground(new java.awt.Color(0, 204, 204));
        jLabel18.setText("K-Nearest Neighbour's Implementation");
        DecTreePanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 400, 20));

        jButton35.setBackground(new java.awt.Color(0, 204, 204));
        jButton35.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton35.setForeground(new java.awt.Color(255, 255, 255));
        jButton35.setText("Start Training");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        DecTreePanel5.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 150, 30));

        jButton36.setBackground(new java.awt.Color(0, 204, 204));
        jButton36.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton36.setForeground(new java.awt.Color(255, 255, 255));
        jButton36.setText("Last Train Result");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        DecTreePanel5.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 170, 30));

        jButton37.setBackground(new java.awt.Color(0, 204, 204));
        jButton37.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setText("Training File");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        DecTreePanel5.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 140, 30));

        jTextArea12.setColumns(20);
        jTextArea12.setEditable(false);
        jTextArea12.setFont(new java.awt.Font("Verdana", 0, 12));
        jTextArea12.setRows(5);
        jScrollPane12.setViewportView(jTextArea12);

        DecTreePanel5.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 1220, 270));

        jButton38.setBackground(new java.awt.Color(0, 204, 204));
        jButton38.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setText("Old Train Log");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        DecTreePanel5.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 170, 30));

        jLabel44.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel44.setForeground(new java.awt.Color(255, 153, 153));
        jLabel44.setText("View old log files:");
        DecTreePanel5.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, 30));

        jLabel45.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel45.setForeground(new java.awt.Color(255, 153, 153));
        jLabel45.setText("Training File:");
        DecTreePanel5.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        jLabel46.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel46.setForeground(new java.awt.Color(255, 153, 153));
        jLabel46.setText("View Result :");
        DecTreePanel5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        jLabel47.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel47.setForeground(new java.awt.Color(255, 153, 153));
        jLabel47.setText("Start training: ");
        DecTreePanel5.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, 30));

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 14));
        jLabel32.setForeground(new java.awt.Color(153, 153, 255));
        DecTreePanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 760, 30));

        TITLE5.setFont(new java.awt.Font("Tahoma", 1, 18));
        TITLE5.setForeground(new java.awt.Color(102, 102, 255));
        TITLE5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/5.png"))); // NOI18N
        DecTreePanel5.add(TITLE5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 230, 120));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 13));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Graph");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        DecTreePanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 140, 30));

        SMAJ_RTNIDS2.addTab("Training", DecTreePanel5);

        DecTreePanel6.setBackground(new java.awt.Color(255, 255, 255));
        DecTreePanel6.setBorder(new javax.swing.border.MatteBorder(null));
        DecTreePanel6.setForeground(new java.awt.Color(255, 153, 153));
        DecTreePanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton39.setBackground(new java.awt.Color(0, 204, 204));
        jButton39.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton39.setForeground(new java.awt.Color(255, 255, 255));
        jButton39.setText("Test");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        DecTreePanel6.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 170, 30));

        jButton40.setBackground(new java.awt.Color(0, 204, 204));
        jButton40.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton40.setForeground(new java.awt.Color(255, 255, 255));
        jButton40.setText("Last Test Result");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        DecTreePanel6.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 170, 30));

        jButton41.setBackground(new java.awt.Color(0, 204, 204));
        jButton41.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton41.setForeground(new java.awt.Color(255, 255, 255));
        jButton41.setText("Testing File");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        DecTreePanel6.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 170, 30));

        jLabel49.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel49.setForeground(new java.awt.Color(255, 153, 153));
        jLabel49.setText("View Result :");
        DecTreePanel6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        jLabel56.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel56.setForeground(new java.awt.Color(255, 153, 153));
        jLabel56.setText("View old log files:");
        DecTreePanel6.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, 30));

        jTextArea13.setColumns(20);
        jTextArea13.setEditable(false);
        jTextArea13.setFont(new java.awt.Font("Verdana", 0, 12));
        jTextArea13.setRows(5);
        jScrollPane13.setViewportView(jTextArea13);

        DecTreePanel6.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 1240, 280));

        jButton42.setBackground(new java.awt.Color(0, 204, 204));
        jButton42.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton42.setForeground(new java.awt.Color(255, 255, 255));
        jButton42.setText("Log Files");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        DecTreePanel6.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 170, 30));

        jLabel57.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel57.setForeground(new java.awt.Color(255, 153, 153));
        jLabel57.setText("Testing File:");
        DecTreePanel6.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        jLabel58.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel58.setForeground(new java.awt.Color(255, 153, 153));
        jLabel58.setText("Start testing: ");
        DecTreePanel6.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, 30));

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel19.setForeground(new java.awt.Color(0, 204, 204));
        jLabel19.setText("K-Nearest Neighbour's Implementation");
        DecTreePanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 400, 20));

        jLabel40.setFont(new java.awt.Font("Verdana", 0, 14));
        jLabel40.setForeground(new java.awt.Color(153, 153, 255));
        DecTreePanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 760, 30));

        TITLE6.setFont(new java.awt.Font("Tahoma", 1, 18));
        TITLE6.setForeground(new java.awt.Color(102, 102, 255));
        TITLE6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/5.png"))); // NOI18N
        DecTreePanel6.add(TITLE6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 230, 120));

        jButton9.setBackground(new java.awt.Color(0, 204, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Graph");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        DecTreePanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 120, 30));

        SMAJ_RTNIDS2.addTab("Testing", DecTreePanel6);

        DecTreePanel7.setBackground(new java.awt.Color(255, 255, 255));
        DecTreePanel7.setBorder(new javax.swing.border.MatteBorder(null));
        DecTreePanel7.setForeground(new java.awt.Color(255, 153, 153));
        DecTreePanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel60.setForeground(new java.awt.Color(255, 153, 153));
        jLabel60.setText("View Log File:");
        DecTreePanel7.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, 30));

        AnalyseDTResult10.setBackground(new java.awt.Color(0, 204, 204));
        AnalyseDTResult10.setFont(new java.awt.Font("Verdana", 1, 14));
        AnalyseDTResult10.setForeground(new java.awt.Color(255, 255, 255));
        AnalyseDTResult10.setText("Last Analysis Result");
        AnalyseDTResult10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyseDTResult10ActionPerformed(evt);
            }
        });
        DecTreePanel7.add(AnalyseDTResult10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, 30));

        jButton61.setBackground(new java.awt.Color(0, 204, 204));
        jButton61.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton61.setForeground(new java.awt.Color(255, 255, 255));
        jButton61.setText("Start Analysis");
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        DecTreePanel7.add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 140, 30));

        AnalyseDTResult13.setBackground(new java.awt.Color(0, 204, 204));
        AnalyseDTResult13.setFont(new java.awt.Font("Verdana", 1, 14));
        AnalyseDTResult13.setForeground(new java.awt.Color(255, 255, 255));
        AnalyseDTResult13.setText("Open Last Log");
        AnalyseDTResult13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyseDTResult13ActionPerformed(evt);
            }
        });
        DecTreePanel7.add(AnalyseDTResult13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 150, 30));

        jButton64.setBackground(new java.awt.Color(0, 204, 204));
        jButton64.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton64.setForeground(new java.awt.Color(255, 255, 255));
        jButton64.setText("Select File");
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        DecTreePanel7.add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 30));

        jLabel65.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel65.setForeground(new java.awt.Color(255, 153, 153));
        jLabel65.setText("Analysis using answer class:");
        DecTreePanel7.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jTextArea14.setColumns(20);
        jTextArea14.setEditable(false);
        jTextArea14.setFont(new java.awt.Font("Verdana", 0, 12));
        jTextArea14.setRows(5);
        jScrollPane14.setViewportView(jTextArea14);

        DecTreePanel7.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1240, 310));

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel20.setForeground(new java.awt.Color(0, 204, 204));
        jLabel20.setText("K-Nearest Neighbour's Implementation");
        DecTreePanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 400, 20));

        TITLE7.setFont(new java.awt.Font("Tahoma", 1, 18));
        TITLE7.setForeground(new java.awt.Color(102, 102, 255));
        TITLE7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/5.png"))); // NOI18N
        DecTreePanel7.add(TITLE7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 230, 110));

        jButton11.setBackground(new java.awt.Color(0, 204, 204));
        jButton11.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Graph");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        DecTreePanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 100, 30));

        SMAJ_RTNIDS2.addTab("Analysis", DecTreePanel7);

        DecTreePanel8.setBackground(new java.awt.Color(255, 255, 255));
        DecTreePanel8.setBorder(new javax.swing.border.MatteBorder(null));
        DecTreePanel8.setForeground(new java.awt.Color(255, 153, 153));
        DecTreePanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea15.setColumns(20);
        jTextArea15.setEditable(false);
        jTextArea15.setFont(new java.awt.Font("Verdana", 1, 14));
        jTextArea15.setForeground(new java.awt.Color(51, 0, 51));
        jTextArea15.setRows(5);
        jTextArea15.setText("     The k-nearest neighbor’s algorithm (k-NN)\n is a method for classifying objects based on closest training examples\n in the feature space. k-NN is a type of instance-based learning, \nor lazy learning where the function is only approximated locally and \nall computation is deferred until classification. \n     An object is classified by a majority vote of its neighbors, \nwith the object being assigned to the class most common amongst\n its k nearest neighbors (k is a positive integer, typically small).\n    The main idea is to choose heuristically optimal k nearest neighbors\n by cross validation technique. If k = 1, then the object is simply assigned\n to the class of its nearest neighbor.");
        jScrollPane15.setViewportView(jTextArea15);

        DecTreePanel8.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 870, 300));

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel21.setForeground(new java.awt.Color(0, 204, 204));
        jLabel21.setText("K-Nearest Neighbour's Information");
        DecTreePanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 400, 20));

        TITLE8.setFont(new java.awt.Font("Tahoma", 1, 18));
        TITLE8.setForeground(new java.awt.Color(102, 102, 255));
        TITLE8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/5.png"))); // NOI18N
        DecTreePanel8.add(TITLE8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 230, 120));

        SMAJ_RTNIDS2.addTab("Help", DecTreePanel8);

        SMAJ_RTNIDS.addTab("K-Nearest Neighbours", SMAJ_RTNIDS2);

        AnalysisPanel.setBackground(new java.awt.Color(255, 255, 255));
        AnalysisPanel.setBorder(new javax.swing.border.MatteBorder(null));

        jButton6.setBackground(new java.awt.Color(255, 153, 153));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Combine Result");
        jButton6.setName("DISPLAY RESULT"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel7.setFont(new java.awt.Font("Verdana", 1, 12));
        jPanel7.setName("TablePanel"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jTextArea16.setColumns(20);
        jTextArea16.setEditable(false);
        jTextArea16.setFont(new java.awt.Font("Verdana", 1, 14));
        jTextArea16.setForeground(new java.awt.Color(102, 0, 102));
        jTextArea16.setRows(5);
        jScrollPane16.setViewportView(jTextArea16);

        jButton7.setBackground(new java.awt.Color(255, 153, 153));
        jButton7.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Open last result");
        jButton7.setName("DISPLAY RESULT"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 153, 153));
        jButton8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Combined Graph");
        jButton8.setName("DISPLAY RESULT"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        TITLE9.setFont(new java.awt.Font("Tahoma", 1, 18));
        TITLE9.setForeground(new java.awt.Color(102, 102, 255));
        TITLE9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/5.png"))); // NOI18N

        javax.swing.GroupLayout AnalysisPanelLayout = new javax.swing.GroupLayout(AnalysisPanel);
        AnalysisPanel.setLayout(AnalysisPanelLayout);
        AnalysisPanelLayout.setHorizontalGroup(
            AnalysisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnalysisPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(411, 411, 411)
                .addComponent(TITLE9, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(865, 865, 865))
            .addGroup(AnalysisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        AnalysisPanelLayout.setVerticalGroup(
            AnalysisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnalysisPanelLayout.createSequentialGroup()
                .addGroup(AnalysisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnalysisPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(AnalysisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(AnalysisPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TITLE9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        SMAJ_RTNIDS.addTab("Analysis", AnalysisPanel);

        ResultPanel.setBackground(new java.awt.Color(255, 255, 255));
        ResultPanel.setBorder(new javax.swing.border.MatteBorder(null));

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View Result");
        jButton4.setName("DISPLAY RESULT"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton5.setBackground(new java.awt.Color(255, 153, 153));
        jButton5.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Open Result");
        jButton5.setName("DISPLAY RESULT"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        TITLE10.setFont(new java.awt.Font("Tahoma", 1, 18));
        TITLE10.setForeground(new java.awt.Color(102, 102, 255));
        TITLE10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/5.png"))); // NOI18N

        javax.swing.GroupLayout ResultPanelLayout = new javax.swing.GroupLayout(ResultPanel);
        ResultPanel.setLayout(ResultPanelLayout);
        ResultPanelLayout.setHorizontalGroup(
            ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanelLayout.createSequentialGroup()
                .addGroup(ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResultPanelLayout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jButton4)
                        .addGap(46, 46, 46)
                        .addComponent(jButton5))
                    .addGroup(ResultPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ResultPanelLayout.createSequentialGroup()
                    .addGap(988, 988, 988)
                    .addComponent(TITLE10)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        ResultPanelLayout.setVerticalGroup(
            ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ResultPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TITLE10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(445, Short.MAX_VALUE)))
        );

        SMAJ_RTNIDS.addTab("Result", ResultPanel);

        TITLE.setFont(new java.awt.Font("Tahoma", 1, 18));
        TITLE.setForeground(new java.awt.Color(102, 102, 255));
        TITLE.setText("Real Time Network Intrusion Detection System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(TITLE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SMAJ_RTNIDS, javax.swing.GroupLayout.PREFERRED_SIZE, 1296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SMAJ_RTNIDS, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SMAJ_RTNIDS.getAccessibleContext().setAccessibleName("SMAJ_RTNIDS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//SHOW RESULT
try
{
    String line;
    FileDialog fd = new FileDialog(this);
fd.setVisible(true);
ResPath= fd.getDirectory()+ fd.getFile();
System.out.println(ResPath);
jTextArea1.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
        while(line!=null){
            jTextArea1.append(line);
            jTextArea1.append("\n");
            line=bin.readLine();            
        }        
        bin.close();        

}
catch(Exception e)
{
}


}//GEN-LAST:event_jButton4ActionPerformed


String retrieve(String line){
StringTokenizer st=new StringTokenizer(line);
int i;
String s="";
for(i=0;i<9;i++){
s=s+st.nextToken(",")+"\t";
}
return s;
}

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
   try{
int i;
String line1,l,line;

StringTokenizer st;
File resf=new File("C:/SMAJ-RTNIDS/DT Result.csv");
FileInputStream ri=new FileInputStream(resf);
BufferedReader bin=new BufferedReader(new InputStreamReader(ri));
File resf1=new File("C:/SMAJ-RTNIDS/KnnResult.csv");
FileInputStream ri1=new FileInputStream(resf1);
BufferedReader bin1=new BufferedReader(new InputStreamReader(ri1));
File ana=new File("C:/SMAJ-RTNIDS/Analysis.csv");
FileOutputStream ri2=new FileOutputStream(ana);
BufferedWriter bout=new BufferedWriter(new OutputStreamWriter(ri2));
for(i=0;i<5;i++){
line=bin.readLine();
line1=bin1.readLine();
st=new StringTokenizer(line1);
l=st.nextToken(",");l=st.nextToken();
l=","+st.nextToken(",")+","+st.nextToken(",")+","+st.nextToken();
bout.newLine();
bout.append(line+l);
}
bout.close();
        
 resf=new File("C:/SMAJ-RTNIDS/Analysis.csv");
ri=new FileInputStream(resf);
bin=new BufferedReader(new InputStreamReader(ri));
String tab="";
line=bin.readLine();
for(i=0;i<5;i++){
line=bin.readLine();
tab=tab+retrieve(line);

tab=tab+"\n";
}
jTextArea16.setText("Result:\n\n"+tab);
   }catch(Exception e){
   
   }
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
// TODO add your handling code here:
 dg=new DATAGEN();
            try {
                if(trPath.equals("")||trPath==null){
                    JOptionPane.showMessageDialog(null,"No file to process");
                }
                
                else{
                    dg.lastfile="";
                    dg.genDecTreeTrain(trPath);
                }                                   
            } catch (IOException ex) {
            }    
try
{
    String line;
ResPath=dg.lasttrain;
jTextArea11.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
        while(line!=null){
            jTextArea11.append(line);
            jTextArea11.append("\n");
            line=bin.readLine();            
        }        
        bin.close();        

}
catch(Exception e)
{
}
}//GEN-LAST:event_jButton27ActionPerformed

private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
// TODO add your handling code here:
if (dg==null)
    JOptionPane.showMessageDialog(null,"WRONG FILE!!!");
else{
    String cmdarray[]=new String[]{"cmd.exe","/c",dg.lasttrain};
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {
        }
try
{
    String line;
ResPath= dg.lasttrain;
System.out.println(ResPath);
jTextArea11.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
        while(line!=null){
            jTextArea11.append(line);
            jTextArea11.append("\n");
            line=bin.readLine();            
        }
        bin.close();        
}
catch(Exception e)
{
}
}
}//GEN-LAST:event_jButton29ActionPerformed

private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
// TODO add your handling code here:
FileDialog fd = new FileDialog(this);
fd.setDirectory("C:\\SMAJ-RTNIDS\\TRAINING FILES");
fd.setVisible(true);

trPath= fd.getDirectory()+ fd.getFile();
System.out.println(trPath);
if(fd.getFile()==null)
{
    jLabel30.setText("");
    trPath=null;
}
else
jLabel30.setText("Current file: "+trPath);

}//GEN-LAST:event_jButton33ActionPerformed

private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
// TODO add your handling code here:
FileDialog fd = new FileDialog(this);
fd.setDirectory("C:\\SMAJ-RTNIDS\\Testing Files");
fd.setVisible(true);
testPath= fd.getDirectory()+ fd.getFile();
System.out.println(testPath);

}//GEN-LAST:event_jButton56ActionPerformed

private void AnalyseDTResult9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyseDTResult9ActionPerformed
// TODO add your handling code here:
            String cmdarray[]=new String[]{"cmd.exe","/c","C:/SMAJ-RTNIDS/DT Result.csv"}    ;
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {
        }

}//GEN-LAST:event_AnalyseDTResult9ActionPerformed

private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
// TODO add your handling code here:
 dg=new DATAGEN();
            try {
                if(trPath.equals("")||trPath==null){
JOptionPane.showMessageDialog(null,"No file selected");
                }
                else
                dg.genDecTreeAnalyseTest(trPath);
                    //dg.genDecTreeAnalyse(trPath);
            } catch (IOException ex) {
            }        
        String cmdarray[]=new String[]{"cmd.exe","/c",dg.lastfile}    ;
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {
        }

}//GEN-LAST:event_jButton59ActionPerformed

private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
// TODO add your handling code here:
       dg=new DATAGEN();
            try {
                if(testPath.equals("")||testPath==null){
                    JOptionPane.showMessageDialog(null,"WRONG FILE!!!");
                }
                else if(jTextField10.getText().isEmpty()||jTextField11.getText().isEmpty()||jTextField12.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"Enter all values!!!");
                }
                else
                {
                    Integer dos,probe,normal;
                    
                    normal=Integer.parseInt(jTextField10.getText());
                    dos=Integer.parseInt(jTextField11.getText());
                    probe=Integer.parseInt(jTextField12.getText());
                    
                    dg.lastfile="";
                    cds.accept(testPath);
                    dg.genDecTreeAnalyseTest("C:/SMAJ-RTNIDS/Convertedtstest.txt",normal,dos,probe);
                }
            } catch (NumberFormatException n) {
                    JOptionPane.showMessageDialog(null,"Enter correct values!!!");
            }        catch (IOException ex) {
            }        
try
{
    String line;
ResPath= dg.lastfile;
System.out.println(ResPath);
jTextArea8.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
        while(line!=null){
            jTextArea8.append(line);
            jTextArea8.append("\n");
            line=bin.readLine();            
        }        
        bin.close();        

}
catch(Exception e)
{
}
    
}//GEN-LAST:event_jButton60ActionPerformed

private void AnalyseDTResult11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyseDTResult11ActionPerformed
// TODO add your handling code here:
    if(dg==null)
        JOptionPane.showMessageDialog(null,"No previous data found!!!");
    else
try
{
    String line;

    ResPath= dg.lastfile;
System.out.println(ResPath);
jTextArea8.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
        while(line!=null){
            jTextArea8.append(line);
            jTextArea8.append("\n");
            line=bin.readLine();            
        }        
        bin.close();        

}
catch(Exception e)
{
}


}//GEN-LAST:event_AnalyseDTResult11ActionPerformed

private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
// TODO add your handling code here:
FileDialog fd = new FileDialog(this);
fd.setDirectory("C:\\SMAJ-RTNIDS\\TRAINING FILES");
fd.setVisible(true);

trPath= fd.getDirectory()+ fd.getFile();
System.out.println(trPath);
if(fd.getFile()==null)
{
    jLabel36.setText("");
    trPath=null;
}
else
jLabel36.setText("Current file: "+trPath);
}//GEN-LAST:event_jButton63ActionPerformed

private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
// TODO add your handling code here:
dg=new DATAGEN();
cds=new convertdatats();
    try {
            //DataGenerator is called after the wireshark converted
                if(testPath.equals("")||testPath==null){
JOptionPane.showMessageDialog(null,"No file to process!!!");
                }
                else
                {
                    dg.lastfile=""; 
                    cds.accept(testPath);
                    dg.genDecTreeTest();
                }
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        }
        /*String cmdarray[]=new String[]{"cmd.exe","/c",dg.lasttest}    ;
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {
        }*/
try
{
    String line;
ResPath= dg.lasttestlog;
System.out.println(ResPath);
jTextArea10.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
        while(line!=null){
            jTextArea10.append(line);
            jTextArea10.append("\n");
            line=bin.readLine();            
        }        
        bin.close();        

}
catch(Exception e)
{
}

}//GEN-LAST:event_jButton28ActionPerformed

private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
// TODO add your handling code here:
if(dg==null)
    JOptionPane.showMessageDialog(null,"No last information to show!!");
else{
    String cmdarray[]=new String[]{"cmd.exe","/c",dg.lasttest}    ;
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {
        }
        
        try
{
    String line;
ResPath= dg.lasttest;
System.out.println(ResPath);
jTextArea10.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
String s;
StringTokenizer st;
line=bin.readLine();
        while(line!=null){
            
            st=new StringTokenizer(line);
            s=st.nextToken(",")+"\t"+st.nextToken(",")+"\t"+st.nextToken();
            
            jTextArea10.append(s);
            jTextArea10.append("\n");
            line=bin.readLine();            
        }        
        bin.close();        

}
catch(Exception e)
{
}
}
}//GEN-LAST:event_jButton30ActionPerformed

private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
// TODO add your handling code here:
FileDialog fd = new FileDialog(this);
fd.setDirectory("C:\\SMAJ-RTNIDS\\Testing Files");
fd.setVisible(true);
testPath= fd.getDirectory()+ fd.getFile();
System.out.println(testPath);
if(fd.getFile()==null)
{
    jLabel34.setText("");
    testPath=null;
}
else

jLabel34.setText("Current file: "+testPath);

}//GEN-LAST:event_jButton34ActionPerformed

private void AnalyseDTResult12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyseDTResult12ActionPerformed
// TODO add your handling code here:
try
{
    String line;
    FileDialog fd = new FileDialog(this);
    fd.setDirectory("C:\\SMAJ-RTNIDS\\Decision Tree\\Analysis Log");
fd.setVisible(true);
ResPath= fd.getDirectory()+ fd.getFile();
System.out.println(ResPath);
jTextArea8.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
        while(line!=null){
            jTextArea8.append(line);
            jTextArea8.append("\n");
            line=bin.readLine();            
        }        
        bin.close();        

}
catch(Exception e)
{
}

}//GEN-LAST:event_AnalyseDTResult12ActionPerformed

private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
// TODO add your handling code here:
try
{
    String line;
    FileDialog fd = new FileDialog(this);
    fd.setDirectory("C:\\SMAJ-RTNIDS\\Decision Tree\\Train Log");
fd.setVisible(true);
ResPath= fd.getDirectory()+ fd.getFile();
System.out.println(ResPath);
jTextArea10.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
        while(line!=null){
            jTextArea10.append(line);
            jTextArea10.append("\n");
            line=bin.readLine();            
        }        
        bin.close();        

}
catch(Exception e)
{
}


}//GEN-LAST:event_jButton31ActionPerformed

private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
// TODO add your handling code here:
try
{
    String line;
    FileDialog fd = new FileDialog(this);
    fd.setDirectory("C:\\SMAJ-RTNIDS\\Decision Tree\\Test Log");
fd.setVisible(true);
ResPath= fd.getDirectory()+ fd.getFile();
System.out.println(ResPath);
jTextArea11.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
        while(line!=null){
            jTextArea11.append(line);
            jTextArea11.append("\n");
            line=bin.readLine();            
        }        
        bin.close();        

}
catch(Exception e)
{
}

}//GEN-LAST:event_jButton32ActionPerformed

private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
flag=flag+1;
ks= new kNNStart();
            try {
                File infile= new File(ktrPath);
                ks.genkNNTrain(infile);
            } catch (IOException ex) {
                Logger.getLogger(SelectFrame.class.getName()).log(Level.SEVERE, null, ex);
            }          
            
             try
{
String line;
ResPath= ks.TrainFile;
jTextArea11.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
        while(line!=null){
            jTextArea12.append(line);
            jTextArea12.append("\n");
            line=bin.readLine();            
        }        
        bin.close();        

}
catch(Exception e)
{
}
// TODO add your handling code here:
}//GEN-LAST:event_jButton35ActionPerformed

private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
System.out.println("Showing Trained File");
String s= ks.TrainFile;
String cmdarray[]=new String[]{"cmd.exe","/c",s};
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {
            Logger.getLogger(SelectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }    
    
// TODO add your handling code here:
}//GEN-LAST:event_jButton36ActionPerformed

private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
   flag=flag+1;
            //Training File is to be opened- KNN
            FileDialog fd = new FileDialog(this);
            fd.show();
            ktrPath= fd.getDirectory()+ fd.getFile();
            jLabel32.setText(ktrPath);
            System.out.println(ktrPath);
            //convertdatats cds= new convertdatats();
            //cds.accept(ktrPath);
            
// TODO add your handling code here:
}//GEN-LAST:event_jButton37ActionPerformed

private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
// TODO add your handling code here:
if(flag!=2)
{
    JDialog j= new JDialog(this, "Error");
}
    
    FileDialog fd = new FileDialog(this);
fd.setDirectory("C:/SMAJ-RTNIDS/KNNLog");

fd.setVisible(true);
String Path= fd.getDirectory()+ fd.getFile();
System.out.println(Path);
String cmdarray[]=new String[]{"cmd.exe","/c",Path}    ;
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {
        }
        

}//GEN-LAST:event_jButton38ActionPerformed

private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
// TODO add your handling code here:
ks= new kNNStart();
File infile= new File(ktestPath);
cds=new convertdatats();
try {
    //DataGenerator is called after the wireshark converted
    if(ktestPath.equals("")||ktestPath==null){
      System.out.println("WRONG FILE!!!");
    }
    else
    {
          cds.accept(ktestPath);
          File f= new File("C:/SMAJ-RTNIDS/Convertedtstest.txt");
          ks.genkNNTest(f);
                 
                }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SelectFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SelectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
try
{
    String line;
ResPath=ks.TestFile;
jTextArea11.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
        while(line!=null){
            jTextArea13.append(line);
            jTextArea13.append("\n");
            line=bin.readLine();            
        }        
        bin.close();        

}
catch(Exception e)
{
}
}//GEN-LAST:event_jButton39ActionPerformed

private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
// TODO add your handling code here:
//Last train Result
System.out.println("Showing Testing File");
String s= ks.TestFile;
String cmdarray[]=new String[]{"cmd.exe","/c",s};
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {
            Logger.getLogger(SelectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }    
          
}//GEN-LAST:event_jButton40ActionPerformed

private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        try {
            // Testing File is to be opened -KNN
            FileDialog fd = new FileDialog(this);
            fd.show();
            
            ktestPath= fd.getDirectory()+ fd.getFile();
            jLabel40.setText(ktestPath);
            System.out.println(ktestPath);
            convertdatats cds=new convertdatats();

            cds.accept(ktestPath);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SelectFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SelectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
// TODO add your handling code here:
}//GEN-LAST:event_jButton41ActionPerformed

private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
if(flag!=2)
{
    JDialog j= new JDialog(this, "Error");
}
    
    FileDialog fd = new FileDialog(this);
fd.setDirectory("C:/SMAJ-RTNIDS/KNNLog");

fd.setVisible(true);
String Path= fd.getDirectory()+ fd.getFile();
System.out.println(Path);
String cmdarray[]=new String[]{"cmd.exe","/c",Path}    ;
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {
        }
        

}//GEN-LAST:event_jButton42ActionPerformed

private void AnalyseDTResult10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyseDTResult10ActionPerformed
if(flag!=2)
{
    Dialog d =new Dialog(this, "Perform Training/Testing first...!!!");
}
   
    try {
            //ANALYSIS OF K-NN
                AnalyseKNN ak =new AnalyseKNN();
                ak.show();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SelectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
}//GEN-LAST:event_AnalyseDTResult10ActionPerformed

private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
flag=flag+1;
ks= new kNNStart();
            try {
                File infile= new File(ktrPath);
                ks.genkNNTrain(infile);
            } catch (IOException ex) {
                Logger.getLogger(SelectFrame.class.getName()).log(Level.SEVERE, null, ex);
            }          
            
             try
{
String line;
ResPath= ks.TrainFile;
jTextArea14.setText("RESULT:"+"\n");
File res =new File(ResPath);
FileInputStream fi=new FileInputStream(res);
BufferedReader bin=new BufferedReader(new InputStreamReader(fi));
line=bin.readLine();
        while(line!=null){
            jTextArea14.append(line);
            jTextArea14.append("\n");
            line=bin.readLine();            
        }        
        bin.close();        

}
catch(Exception e)
{
}
            
}//GEN-LAST:event_jButton61ActionPerformed

private void AnalyseDTResult13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyseDTResult13ActionPerformed
// TODO add your handling code here:
if(flag!=2)
{
    JDialog j= new JDialog(this, "Error");
}
    
    FileDialog fd = new FileDialog(this);
fd.setDirectory("C:/SMAJ-RTNIDS/KNNLog");

fd.setVisible(true);
String Path= fd.getDirectory()+ fd.getFile();
System.out.println(Path);
String cmdarray[]=new String[]{"cmd.exe","/c",Path}    ;
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {
            Logger.getLogger(SelectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}//GEN-LAST:event_AnalyseDTResult13ActionPerformed

private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
   flag=flag+1;
            //Training File is to be opened- KNN
            FileDialog fd = new FileDialog(this);
            fd.show();
            ktrPath= fd.getDirectory()+ fd.getFile();
            jLabel32.setText(ktrPath);
            System.out.println(ktrPath);
            //convertdatats cds= new convertdatats();
            //cds.accept(ktrPath);
            
}//GEN-LAST:event_jButton64ActionPerformed

private void AnalyseDTResult15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyseDTResult15ActionPerformed
    // TODO add your handling code here:
            String cmdarray[]=new String[]{"cmd.exe","/c","C:/SMAJ-RTNIDS/Analysis.csv"}    ;
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {

}//GEN-LAST:event_AnalyseDTResult15ActionPerformed
}
private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
     String cmdarray[]=new String[]{"cmd.exe","/c","C:/SMAJ-RTNIDS/Analysis.csv"}    ;
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {
        }
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    String line;
    FileDialog fd = new FileDialog(this);
    fd.setDirectory("C:\\SMAJ-RTNIDS");
fd.setVisible(true);
ResPath= fd.getDirectory()+ fd.getFile();
    
    String cmdarray[]=new String[]{"cmd.exe","/c",ResPath}    ;
        try {
            Runtime.getRuntime().exec(cmdarray);
        } catch (IOException ex) {

}                                                 

}//GEN-LAST:event_jButton5ActionPerformed

private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
// TODO add your handling code here:
    Graph g;
    if(dg==null)
        JOptionPane.showMessageDialog(null,"No information to plot");
    else
        g=new Graph(dg);
}//GEN-LAST:event_jButton43ActionPerformed

private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
// TODO add your handling code here:
Graph g;
if(dg==null)
   JOptionPane.showMessageDialog(null,"No information to plot!!");
else
    g=new Graph(dg,1);

}//GEN-LAST:event_jButton44ActionPerformed

private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
// TODO add your handling code here:
Graph g;
if(dg==null)
   JOptionPane.showMessageDialog(null,"No information to plot!!");
else
g=new Graph(dg,1,2);

}//GEN-LAST:event_jButton45ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
     FinalAnalyseChartPanel cp;
    if(dg==null||ks==null)
   JOptionPane.showMessageDialog(null,"No information to plot!!");
else
        
   cp =new FinalAnalyseChartPanel(ks, GUI.kNNStart.Train, dg);

}//GEN-LAST:event_jButton8ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
   ChartPanel cp =new ChartPanel(GUI.kNNStart.Train);
   
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
ChartPanel cp =new ChartPanel(GUI.kNNStart.Test);
    // TODO add your handling code here:
}//GEN-LAST:event_jButton9ActionPerformed

private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
AnalyseChartPanel cp =new AnalyseChartPanel(ks, GUI.kNNStart.Train);
}//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SelectFrame().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalyseDTResult10;
    private javax.swing.JButton AnalyseDTResult11;
    private javax.swing.JButton AnalyseDTResult12;
    private javax.swing.JButton AnalyseDTResult13;
    private javax.swing.JButton AnalyseDTResult15;
    private javax.swing.JButton AnalyseDTResult9;
    private javax.swing.JPanel AnalysisPanel;
    private javax.swing.JPanel DecTreePanel1;
    private javax.swing.JPanel DecTreePanel2;
    private javax.swing.JPanel DecTreePanel3;
    private javax.swing.JPanel DecTreePanel4;
    private javax.swing.JPanel DecTreePanel5;
    private javax.swing.JPanel DecTreePanel6;
    private javax.swing.JPanel DecTreePanel7;
    private javax.swing.JPanel DecTreePanel8;
    private javax.swing.JPanel ResultPanel;
    private javax.swing.JTabbedPane SMAJ_RTNIDS;
    private javax.swing.JTabbedPane SMAJ_RTNIDS1;
    private javax.swing.JTabbedPane SMAJ_RTNIDS2;
    private javax.swing.JLabel TITLE;
    private javax.swing.JLabel TITLE1;
    private javax.swing.JLabel TITLE10;
    private javax.swing.JLabel TITLE2;
    private javax.swing.JLabel TITLE3;
    private javax.swing.JLabel TITLE4;
    private javax.swing.JLabel TITLE5;
    private javax.swing.JLabel TITLE6;
    private javax.swing.JLabel TITLE7;
    private javax.swing.JLabel TITLE8;
    private javax.swing.JLabel TITLE9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    // End of variables declaration//GEN-END:variables

void initVariable(){

}
}

